### ISSUE TITLE
React 16.6 & npx

### ISSUE THREAD

**Issue by xgqfrms** [xgqfrms/React#14]
# React 16.6 & npx

https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

**Comment by xgqfrms** [comment]
# npm

> xyz-app-cli

https://www.npmjs.com/~xgqfrms

**Comment by xgqfrms** [comment]
# new version node bug?

> After I upgrade node, the error occurred, what's wrong with this?

> v8.9.1 => v10.13.0

```sh

0 info it worked if it ends with ok
1 verbose cli [ 'H:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xiagq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'app' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'preapp', 'app', 'postapp' ]
5 info lifecycle web-components@1.1.1~preapp: web-components@1.1.1
6 info lifecycle web-components@1.1.1~app: web-components@1.1.1
7 verbose lifecycle web-components@1.1.1~app: unsafe-perm in lifecycle true
8 verbose lifecycle web-components@1.1.1~app: PATH: C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\FastView\web-components\node_modules\.bin;H:\Python27\;H:\Python27\Scripts;H:\Python36\Scripts\;H:\Python36\;H:\Program Files (x86)\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;H:\Program Files\TortoiseSVN\bin;H:\Microsoft VS Code\bin;H:\Program Files\Sublime Text 3\;C:\Program Files\TortoiseGit\bin;H:\Program Files (x86)\Yarn\bin\;H:\nginx-1.13.12;C:\WINDOWS\System32\OpenSSH\;H:\MySQL\mysql-5.7.22-winx64\bin;C:\Program Files\wkhtmltopdf\bin;H:\Program Files\MongoDB\Server\4.0\bin;H:\Program Files\nodejs\;C:\Users\xiagq\AppData\Local\Microsoft\WindowsApps;H:\Microsoft VS Code\bin;C:\Users\xiagq\AppData\Local\GitHubDesktop\bin;C:\Users\xiagq\AppData\Local\Yarn\bin;H:\Programs\Fiddler;C:\Users\xiagq\AppData\Local\Microsoft\WindowsApps;C:\Users\xiagq\AppData\Roaming\npm
9 verbose lifecycle web-components@1.1.1~app: CWD: E:\FastView\web-components
10 silly lifecycle web-components@1.1.1~app: Args: [ '/d /s /c',
10 silly lifecycle   'npm run rmrf-all && webpack -p && npm run rmrf-map' ]
11 silly lifecycle web-components@1.1.1~app: Returned: code: 2  signal: null
12 info lifecycle web-components@1.1.1~app: Failed to exec app script
13 verbose stack Error: web-components@1.1.1 app: `npm run rmrf-all && webpack -p && npm run rmrf-map`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xiagq\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid web-components@1.1.1
15 verbose cwd E:\FastView\web-components
16 verbose Windows_NT 10.0.17134
17 verbose argv "H:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xiagq\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "app"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error web-components@1.1.1 app: `npm run rmrf-all && webpack -p && npm run rmrf-map`
22 error Exit status 2
23 error Failed at the web-components@1.1.1 app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```

**Comment by xgqfrms** [comment]
https://github.com/nodejs/node/issues/24013

**Comment by xgqfrms** [comment]
https://facebook.github.io/create-react-app/docs/getting-started
https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

https://reactjs.org/docs/react-dom.html

**Comment by xgqfrms** [comment]
https://blog.bitsrc.io/how-to-use-sass-and-css-modules-with-create-react-app-83fa8b805e5e
